[changelog]
header = "## Changes\n\n"
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group }}
{% for commit in commits %}
- {{ commit.message | trim }}
{% endfor %}

{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_commits = true
tag_pattern = "^v"
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^docs", group = "Docs" },
  { message = "^refactor", group = "Refactor" },
  { message = "^perf", group = "Performance" },
  { message = "^test", group = "Tests" },
  { message = "^build", group = "Build" },
  { message = "^ci", group = "CI" },
  { message = "^chore", group = "Chore" },
  { message = ".*", group = "Others" }
]
