name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      artifact_prefix: build
