name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    permissions:
      contents: read
    uses: ./.github/workflows/reusable-build.yml
    with:
      artifact_prefix: release

  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    needs: [changelog, build-release]
    permissions:
      contents: write
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: release-*
          path: dist
          merge-multiple: true

      - name: Publish Release Assets
        uses: softprops/action-gh-release@v3
        with:
          files: dist/*
          body: ${{ needs.changelog.outputs.release_body }}
